### PR TITLE
[FIX] npm t8r: Handle npm optionalDependencies correctly

### LINKED ISSUE #51: npm translator should mind about optionalDependencies
## Expected Behavior
The build / serve should not fail in case any `optionalDependencies` are not available.

## Current Behavior
The build fails, due to the module beeing not found.

## Steps to reproduce the issue
Add any optional dependency to the package.json of an NPM project. Try to build / serve.

## Affected components
- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [x] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Stack trace/log output
```
[13:51:24] Error: [npm translator] Failed to locate module <anymodule> from <anypath> - Error: Could not locate module <anymodule> via resolve logic (error: Cannot find module '<anymodule>/package.json' from '<anypath>') or in a collection
    at resolveModulePath.then.then.catch.catch (<anypath>\node_modules\@ui5\project\lib\translators\npm.js:219:10)
```

### PR DESCRIPTION
**Pull request by RandomByte**
In the past, optionalDependencies that could not be located caused a
"Failed to locate module".

Fixes #51

### CODE REVIEW

File: lib/translators/npm.js [hunk 1]
```diff
@@ -32,6 +32,26 @@ class NpmTranslator {
...
+		// Note: optionalDependencies are treated the same as devDependencies in the npm translator
+		if (pkg.optionalDependencies) {
+			for (let depName in pkg.optionalDependencies) {
+				if (pkg.optionalDependencies.hasOwnProperty(depName)) {
+					// Remove entry from "hard" dependencies map
+					if (dependencies[depName]) {
+						delete dependencies[depName];
+					}
+					// Add to optional dependencies map (of not already done)
+					if (!optDependencies[depName]) {
```
Comment (matz3) [inline lib/translators/npm.js]: "hasOwnProperty" check here?

Comment (RandomByte) [reply lib/translators/npm.js]: Done

**Comment by RandomByte** [comment]
Had to rebase due to conflicts
